#!/usr/bin/env python3
"""Batch verify (goal_state, tactic) pairs using Pantograph.

Takes unverified pairs generated by Codex/LLM and checks each one
against Lean's kernel via Pantograph. Only verified pairs are kept.

Input JSONL format (one per line):
    {"goal_state": "forall (n : Nat), n + 0 = n", "proposed_tactic": "simp"}

Output JSONL format (verified pairs in SFT training format):
    {"prompt": "forall (n : Nat), n + 0 = n:::", "completion": "simp"}

Usage:
    python scripts/verify_pairs.py \
        --input unverified_pairs.jsonl \
        --output verified_pairs.jsonl \
        --lean-project lean \
        --pantograph vendor/Pantograph/.lake/build/bin/repl
"""

import argparse
import json
import logging
import time
from pathlib import Path

from openproof_ml.data.formatting import BANNED_TACTICS, format_training_example
from openproof_ml.search.pantograph_client import PantographClient

logger = logging.getLogger(__name__)


def verify_pair(pg: PantographClient, goal_state: str, tactic: str) -> dict | None:
    """Verify a (goal_state, tactic) pair via Pantograph.

    Returns a dict with verification info if the tactic succeeds, None if it fails.
    Only returns results where the tactic actually makes progress (closes goal
    or reduces remaining goals).
    """
    state_id = pg.start_goal(goal_state)
    if state_id is None:
        return None

    try:
        result = pg.try_tactic(state_id, 0, tactic)
        if not result.success or result.new_state_id is None:
            return None

        closes_goal = len(result.remaining_goals) == 0
        remaining = result.remaining_goals

        # Only keep tactics that close the goal entirely
        if not closes_goal:
            return None

        return {
            "closes_goal": closes_goal,
            "remaining_goals": len(remaining),
        }
    except Exception:
        return None
    finally:
        for sid in [state_id] + ([result.new_state_id] if 'result' in dir() and result.new_state_id else []):
            try:
                pg.delete_goal(sid)
            except Exception:
                pass


def main():
    parser = argparse.ArgumentParser(description="Batch verify tactic pairs with Pantograph")
    parser.add_argument("--input", required=True, help="Unverified pairs JSONL")
    parser.add_argument("--output", required=True, help="Verified pairs JSONL (SFT format)")
    parser.add_argument("--lean-project", default="lean", help="Lean project path")
    parser.add_argument("--pantograph", default="vendor/Pantograph/.lake/build/bin/repl")
    parser.add_argument("--reject-output", help="Optional: write rejected pairs here")
    args = parser.parse_args()

    # Load unverified pairs
    pairs = []
    with open(args.input) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            pairs.append(json.loads(line))

    logger.info(f"Loaded {len(pairs)} unverified pairs")

    # Start Pantograph
    pg = PantographClient(args.lean_project, args.pantograph)
    logger.info("Starting Pantograph (loading Mathlib)...")
    pg.start()
    logger.info("Pantograph ready")

    # Verify each pair
    verified = []
    rejected = []
    start_time = time.monotonic()

    for i, pair in enumerate(pairs):
        goal = pair.get("goal_state", "").strip()
        tactic = pair.get("proposed_tactic", "").strip()

        if not goal or not tactic:
            rejected.append(pair)
            continue

        # Filter banned tactics
        lower = tactic.lower()
        if any(lower == b or lower.startswith(f"{b} ") or lower.startswith(f"{b};") for b in BANNED_TACTICS):
            rejected.append(pair)
            continue

        # Restart Pantograph if dead
        if not pg.is_alive():
            logger.info(f"  Pantograph died at pair {i}, restarting...")
            pg.close()
            pg = PantographClient(args.lean_project, args.pantograph)
            pg.start()

        # Verify -- only keep tactics that close the goal
        result = verify_pair(pg, goal, tactic)
        if result is not None:
            example = format_training_example(goal, tactic)
            example["closes_goal"] = result["closes_goal"]
            verified.append(example)
        else:
            rejected.append(pair)

        if (i + 1) % 1000 == 0:
            elapsed = time.monotonic() - start_time
            rate = (i + 1) / elapsed
            logger.info(
                f"  {i+1}/{len(pairs)} verified={len(verified)} "
                f"rejected={len(rejected)} rate={rate:.0f}/s"
            )

    pg.close()
    elapsed = time.monotonic() - start_time

    # Write verified pairs
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        for pair in verified:
            f.write(json.dumps(pair) + "\n")

    # Write rejected pairs
    if args.reject_output and rejected:
        reject_path = Path(args.reject_output)
        reject_path.parent.mkdir(parents=True, exist_ok=True)
        with open(reject_path, "w") as f:
            for pair in rejected:
                f.write(json.dumps(pair) + "\n")

    logger.info(f"\n=== Verification complete in {elapsed:.0f}s ===")
    logger.info(f"Input:    {len(pairs)}")
    logger.info(f"Verified: {len(verified)} ({100*len(verified)/max(len(pairs),1):.1f}%)")
    logger.info(f"Rejected: {len(rejected)}")
    logger.info(f"Rate:     {len(pairs)/elapsed:.0f} pairs/sec")
    logger.info(f"Output:   {args.output}")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
    main()
